name: CI

on:
  push:
    branches:
      - main
      - "v*.[0-9]"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 23.7.0
      - name: Install Dependencies
        run: yarn
      - name: Check Format
        run: yarn check-format
      - name: Run Tests
        run: yarn test
      # - name: Coveralls GitHub Action
      #   uses: coverallsapp/github-action@v2
