name: Release new version

on:
  pull_request:
    branches:
      - main
    types: closed

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  release:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Create Release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
        with:
          tag: ${{ github.event.pull_request.title }}
          name: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
